---
title: "Yukon River Fall Chum MSA"
output:
#  html_document:
#    toc: true
#    theme: united
  word_document:
    reference_docx: defalult-style_01.docx
    toc: false
#    highlight: zenburn
---


```{r get_data, message=FALSE,echo=FALSE,error=FALSE,warning=FALSE}
#-------------------------------------------------------------------------------
# Setup file directories 
#-------------------------------------------------------------------------------
# Clear up existing files 
rm(list = ls(all = TRUE))
#-------------------------------------------------------------------------------
# Standard 
#-------------------------------------------------------------------------------
# Main <- 'C:/Projects/Yukon_River/Fall_Chum/MSA/' 
# fdr <- paste0(Main, 'R_functions/')  # R functions
#-------------------------------------------------------------------------------
# Rprojects 
#-------------------------------------------------------------------------------
fdr <- './R_functions/'
#===============================================================================
#  1.0: Run MSA
#===============================================================================
inSeason <- TRUE 
# Set year 
this.year <- 2020
#-------------------------------------------------------------------------------
#  1.1: Set MSA data directory and file names 
#-------------------------------------------------------------------------------

source(paste0(fdr,'Yukon_Chum_MSA_RUN.R'))  
stbreak <- stb(this.year)
Pilot.total <- mlist[mlist$Strata==100,]
Pilot.summer <-mlist[mlist$Strata==101,]
Pilot.fall <- mlist[mlist$Strata==102,]
#-------------------------------------------------------------------------------
#  1.1: Set MSA data directory and file names 
#-------------------------------------------------------------------------------
#===============================================================================
#  2.0: Read summary data
#===============================================================================
#-------------------------------------------------------------------------------
#  2.1: Read Summer vs. Fall % data
#-------------------------------------------------------------------------------
# Read MSA Strata data
Pilot.d.min.max <- read.csv(paste0(wd_Sum,'Pilot_d_min_max.csv'),stringsAsFactors = FALSE)

# Read MSA Strata data
Pilot.hsft <- read.csv(paste0(wd_Sum,'Pilot_sft.csv'),stringsAsFactors = FALSE)
# Find the number of years in the data 
years <- unique(Pilot.hsft$Year)
years <- years[order(years)]
# number of years
ny <- length(years)

############################################################################
#  Add kniter and rmarkdown libraries
############################################################################
library(knitr)
library(rmarkdown)
```

```{r,fig.width=9, fig.height = 5,echo=FALSE,dpi=400}
# Pilot Station timing 
par(mfrow=c(1,1),mar = c(2,2,2,2),oma = c(3,3,3,3),yaxs='i',bty='l',las=1)
  rstr.y <- rstr[rstr$Year==this.year,]
  xlims<-c(min(stbreak),max(stbreak))
  plot(Run~Date, type='h',lwd=4,col='gray',data=Pilot,xlim=xlims,xaxt='n')
  axis.Date(1, at = stbreak,format= "%b%d",cex=0.6)
  abline(v=c(rstr.y$Strata_Start_Date),col=4,lwd=2)
mtext(paste("Sampling Strata"), side = 3, line = 0, outer = TRUE,cex=1.5)
mtext('Pilot Station Run', side = 2, line = 1.5, las=0, outer = TRUE,cex=1.5)
mtext("Date", side = 1, line = 1, outer = TRUE,cex=1.5)
```
Figure 1.  Pilot Station Sample Strata. 



```{r,fig.width=9, fig.height = 5,echo=FALSE,dpi=400}
#-------------------------------------------------------------------------------
#  Plot mean stock proportion by sampling strata 
#-------------------------------------------------------------------------------
# Pilot Station timing 
Pilot.stp <- Pilot.m[,c('Year','Strata','Run', ststocks)]
Pilot.stp[,ststocks] <- 100*Pilot.stp[,ststocks] /Pilot.stp$Run
Pilot.stpl <- melt(Pilot.stp[,c('Year','Strata',ststocks)], 
                   id.vars = c('Year','Strata'), variable.name = "group", value.name = "percent") 
Pilot.stpl <- Pilot.stpl[order(Pilot.stpl$Year,Pilot.stpl$Strata),]
gname <- stockID[stockID$grpID %in%ststockID,c('GroupName')]      
names(gname) <- ststockID
# Base plot 			
par(mfrow=c(1,1),mar=c(5.1, 4.1, 4.1, 9.1),yaxs='i',bty='l',las=1) 
temp1 <- Pilot.stpl[Pilot.stpl$group==ststockID[1],]
plot(order(temp1$Strata),type='n', xlim=c(1,9),ylim=c(0,100), ylab='Stock Percent',xlab='Sample Period Number')
for (i in 1:6){
  lines(percent~Strata, type ='o',lwd=2,col=i,pch=i,data=Pilot.stpl[Pilot.stpl$group==ststockID[i],])
}
title(main = this.year)
par(xpd=TRUE)
legend('topright',legend = gname, inset = c(- 0.2, 0),col = c(1:6), pch=c(1:6),lty=1,lwd=2,bty = 'n')
mtext('Stock %', side = 2, line = 1,las=0, outer = TRUE)
mtext("Sampling Strata", side = 1, line = 1, outer = TRUE)

```
Figure 2.  Mean stock proportion by sampling strata.



```{r,fig.width=9, fig.height = 5,echo=FALSE,dpi=400}
#-------------------------------------------------------------------------------
#  Plot mean stock proportion by Standard Strata
#-------------------------------------------------------------------------------
gname <- stockID[stockID$grpID %in%ststockID,c('GroupName')]      
names(gname) <- ststockID

par(mfrow=c(1,1),mar = c(2,2,2,2),oma = c(3,3,3,3),yaxs='i',bty='l',las=1)
temp1 <- with(Pilot.d.min.max, Pilot.d.min.max[group ==ststockID[1],])
plot(order(temp1$stbreak),type='n', xlim=c(1,9),ylim=c(0,100), ylab='',xlab='',
     yaxt='n',xaxt='n')
axis(2, seq(0,100,20),las=2, font=2 )
axis(1, seq(1,9,1), labels = stbl,tick=1)
for(i in 1:6){
  temp <- with(Pilot.d.min.max, Pilot.d.min.max[group ==ststockID[i],])  
  temp <- temp[order(temp$stbreak),]
  with(temp, lines(stbreak,Mean, type='o',lwd=2,col=i,pch=i))
}
txt <- c(gname)
legend('topright',legend=txt,col=c(1:6),pch=c(1:6),lty=1,lwd=2,bty='n')
mtext(paste("Run stock proportion "), side = 3, line = 0, outer = TRUE)
mtext('Stock %', side = 2, line = 1,las=0, outer = TRUE)
mtext("Dates ", side = 1, line = 1, outer = TRUE)

```
Figure 3.  Mean stock proportion by standrad sampling strata.


```{r,fig.width=9, fig.height = 9,echo=FALSE,dpi=400}
par(mfrow=c(4,2),mar = c(2,2,2,2),oma = c(3,3,3,3),yaxs='i',bty='l')
fig.stock.id <- c(4,7,8,11,10,19,16,3)
for(j in 1:8){
  temp1 <- with(Pilot.d.min.max, Pilot.d.min.max[group ==fig.stock.id[j],])
  temp1 <- temp1[order(temp1$stbreak),]
  plot(Mean~stbreak,data=temp1, type='n',xlim=c(1,9),ylim=c(0,100), 
       yaxt='n',xaxt='n',main=unique(temp1$GroupName))
  axis(2, seq(0,100,20),las=2, label=FALSE)
  if(j %in% c(1,3,5,7)) {axis(2, seq(0,100,20),las=2, font=2)}
  axis(1,seq(1,9,1), labels = FALSE,tick=1)
  if(j %in% c(7:8)) {axis(1, seq(1,9,1), labels = stbl,tick=1)}
  with(temp1,polygon(c(stbreak,rev(stbreak)),c(Min,rev(Max)),col=tcol('gray',0),border=NA))
  lines(percent~stbreak,lwd=2,col=2, data=Pilot.sd[Pilot.sd$ group ==fig.stock.id[j],])
  }

mtext(paste("Run stock proportion "), side = 3, line = 0, outer = TRUE)
mtext('Stock %', side = 2, line = 1, outer = TRUE)
mtext("Dates ", side = 1, line = 1, outer = TRUE)

```
Figure 4.  Mean stock proportion by standrad sampling strata.



```{r,fig.width=9, fig.height = 9,echo=FALSE,dpi=400}
  par(mfrow=c(5,5),mar = c(2,2,2,2),oma = c(3,3,3,3),yaxs='i',bty='l') 
  for(i in 1:ny){
    temp <- with(Pilot.hsft, Pilot.hsft[Year==years[i],])
    plot(Summer~stbreak, type ='o',col=4, xlim=c(1,9),ylim=c(0,100), 
         yaxt='n',xaxt='n',lwd = 2, data=temp,main=years[i])
    lines(Fall~stbreak,type ='o',col=2,lwd = 2, data=temp)
    axis(2, seq(0,100,20),las=2, labels=NA)
    if (years[i] %in% c(1999,2005, 2010,2015, 2020)) axis(2, seq(0,100,20),las=2, font=2)
    axis(1, seq(1,9,1),labels = NA,cex.axis = 0.9)
    if (years[i] > 2016) axis(1, seq(1,9,1), labels = stbl,cex.axis = 0.9)
  }
# This year 
 plot(Summer~stbreak, type ='o',col=4, xlim=c(1,9),ylim=c(0,100), 
     yaxt='n',xaxt='n',lwd = 2, data=Pilot.sft,main=this.year)
 lines(Fall~stbreak,type ='o',col=2,lwd = 2, data=Pilot.sft)
 axis(2, seq(0,100,20),las=2, font=2)
 axis(1, seq(1,9,1), labels = stbl,cex.axis = 0.9)
 
  mtext(paste("Summer vs. Fall "), side = 3, line = 0, outer = TRUE,cex=1.5)
  mtext('Stock %', side = 2, line = 1, outer = TRUE,cex=1.5)
  mtext("Dates ", side = 1, line = 1, outer = TRUE,cex=1.5)
```
Figure 5.  Summer vs. Fall All Strata.


```{r,fig.width=9, fig.height = 9,echo=FALSE,dpi=400}
  par(mfrow=c(5,5),mar = c(2,2,2,2),oma = c(3,3,3,3),yaxs='i',bty='l') 
    for(i in 1:ny){
    temp <- with(Pilot.hsft, Pilot.hsft[Year==years[i],])
    plot(Summer~stbreak, type ='o',col=4, xlim=c(4,6),ylim=c(0,100), 
         yaxt='n',xaxt='n',lwd = 2, data=temp,main=years[i])
    lines(Fall~stbreak,type ='o',col=2,lwd = 2, data=temp)
    axis(2, seq(0,100,20),las=2, labels=NA)
    if (years[i] %in% c(1999,2005, 2010,2015, 2020)) axis(2, seq(0,100,20),las=2, font=2)
    axis(1, seq(1,9,1),labels = NA,cex.axis = 0.9)
    if (years[i] > 2016) axis(1, seq(1,9,1), labels = stbl,cex.axis = 0.9)
    }
# This year 
  plot(Summer~stbreak, type ='o',col=4, xlim=c(4,6),ylim=c(0,100), 
       yaxt='n',xaxt='n',lwd = 2, data=Pilot.sft,main=this.year)
  lines(Fall~stbreak,type ='o',col=2,lwd = 2, data=Pilot.sft)
  axis(2, seq(0,100,20),las=2, font=2)
  axis(1, seq(1,9,1), labels = stbl,cex.axis = 0.9)
  
  mtext(paste("Summer vs. Fall "), side = 3, line = 0, outer = TRUE,cex=1.5)
  mtext('Stock %', side = 2, line = 1, las=0, outer = TRUE,cex=1.5)
  mtext("Dates ", side = 1, line = 1, outer = TRUE,cex=1.5)

```
Figure 6.  Summer vs. Fall  3 Periods.


